### ISSUE TITLE
Missing Attributes

### ISSUE THREAD

**Issue by akeslo** [edwork/homeassistant-peloton-sensor#16]
Awesome integration thanks for this!

I've noticed recently however that not all attributes are populating like they used to.  I don't see any errors specifically in the logs.  Is this a known issue?

Thanks.

![image](https://user-images.githubusercontent.com/3003773/126725683-6cd16d43-8536-4db3-b959-0067333603b5.png)
![image](https://user-images.githubusercontent.com/3003773/126725697-f60de007-34c4-4f1a-a8ed-6a0ee800de73.png)

**Comment by akeslo** [comment]
Looks like this was mentioned here: #15 and already being worked on. Thanks!!

**Comment by j6s33m** [comment]
I see references of these reporting errors being fixed in the API update, but I am not seeing any fixes with my sensors. Almost all of them are still not reporting.

**Comment by akeslo** [comment]
> I see references of these reporting errors being fixed in the API update, but I am not seeing any fixes with my sensors. Almost all of them are still not reporting.

Same here, has there been any updates on this?

**Comment by Finagain** [comment]
The API update I submitted was never committed to the project so I closed it.  I sent you an invite to my repository with a working sensor.py file.  That is the ONLY file I modified.  I also added Heart Rate Zones.

**Comment by akeslo** [comment]
> The API update I submitted was never committed to the project so I closed it. I sent you an invite to my repository with a working sensor.py file. That is the ONLY file I modified. I also added Heart Rate Zones.

@Finagain thank you, you're file is working great!

**Comment by edwork** [comment]
New Release Published - Version 0.6.0!  

https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.6.0

Please follow #18 for the HACS related support, planning on adding that next.
