### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by dgoldy56** [edwork/homeassistant-peloton-sensor#17]
updated to 0.5.3 but still data not populating (worked fine before) only date/time and class rank

**Comment by Finagain** [comment]
The API was changed.  Here are the changes I made.  The "Current" workout doesn't work with my changes (I will fix that later) but here is what I changed on the sensor.py file.

`def update(self):
        """Fetch new state data for the sensor."""

        conn = pylotoncycle.PylotonCycle(self.user, self.password)
        workouts = conn.GetRecentWorkouts(2)
        workout_1 = workouts[0]
        w_id_1 = workout_1["id"]
        stats_1 = conn.GetWorkoutMetricsById(w_id_1)

        if (workout_1["status"]== 'COMPLETE'):
            self._state = 'Complete'
        elif (workout_1["status"]== 'IN_PROGRESS'):
            self._state = 'Active'
         
        else:
            self._state = workout["UNKNOWN"]

        # Attempting to handle errors in case the API changes
        try:
            self._attributes.update({"Workout Type":str(workout_1["fitness_discipline"])})
            self._attributes.update({"Ride Title":str(workout_1["ride"]["title"])})
            self._attributes.update({"Description":str(workout_1["ride"]["description"])})
            self._attributes.update({"Start Time":str(workout_1["start_time"])})
            self._attributes.update({"End Time":str(workout_1["end_time"])})
            self._attributes.update({"Duration Min":str((workout_1["ride"]["duration"])//60)})
            self._attributes.update({"Leaderboard Rank":str(workout_1["leaderboard_rank"])})
            self._attributes.update({"Leaderboard Users":str(workout_1["total_leaderboard_users"])})
            self._attributes.update({"Output Kj":str((workout_1["total_work"]//1000)+(workout_1["total_work"]%1000>0))})
            self._attributes.update({"Distance Mi":str(stats_1["summaries"][1]["value"])})
            self._attributes.update({"Calories KCal":str(int(stats_1["summaries"][2]["value"]))})
            self._attributes.update({"Heart Rate Average Bpm":str(stats_1["metrics"][4]["average_value"])})
            self._attributes.update({"Heart Rate Max Bpm":str(stats_1["metrics"][4]["max_value"])})
            self._attributes.update({"Resistance Average %":str(stats_1["metrics"][2]["average_value"])})
            self._attributes.update({"Resistance Max %":str(stats_1["metrics"][2]["max_value"])})
            self._attributes.update({"Speed Average Mph":str(stats_1["metrics"][3]["average_value"])})
            self._attributes.update({"Speed Max Mph":str(stats_1["metrics"][3]["max_value"])})
            self._attributes.update({"Speed Average Kph":str(round(((stats_1["metrics"][3]["average_value"])*1.60934),2))})
            self._attributes.update({"Speed Max Kph":str(round(((stats_1["metrics"][3]["max_value"])*1.60934),2))})
            self._attributes.update({"Cadence Average Rpm":str(stats_1["metrics"][1]["average_value"])})
            self._attributes.update({"Cadence Max Rpm":str(stats_1["metrics"][1]["max_value"])})
            self._attributes.update({"Power Average W":str(stats_1["metrics"][0]["average_value"])})
            self._attributes.update({"Power Max W":str(stats_1["metrics"][0]["max_value"])})
            self._attributes.update({"Total Work":str(workout_1["overall_summary"]["total_work"])})
            self._attributes.update({"Instructor":str(workout_1["instructor_name"])})
            self._attributes.update({"Workout Image":str(workout_1["ride"]["image_url"])})
            #
            # #Current metrics
            #
            self._attributes.update({"Heart Rate Bpm":str(stats_1["metrics"][4]["average_value"])})
            self._attributes.update({"Resistance %":str(stats_1["metrics"][2]["average_value"])})
            self._attributes.update({"Speed Mph":str(workout_1["overall_summary"]["speed"])})
            self._attributes.update({"Speed Kph":str(round(((workout_1["overall_summary"]["speed"])*1.60934),2))})
            self._attributes.update({"Cadence Rpm":str(workout_1["overall_summary"]["cadence"])})
            self._attributes.update({"Power W":str(workout_1["overall_summary"]["power"])})
        except:
            print("Error - Check to make sure the API hasn't changed")
`

**Comment by dgoldy56** [comment]
Works thank you appreciate your work and efforts

**Comment by kylewilliams321** [comment]
Hey @Finagain - I'm having trouble getting mine to work. 
This is all I see:
![image](https://user-images.githubusercontent.com/39958233/134699306-99798bba-367b-46f4-a70d-f98f12bc06d0.png)

**Comment by Finagain** [comment]
> Hey @Finagain - I'm having trouble getting mine to work.
> This is all I see:
> ![image](https://user-images.githubusercontent.com/39958233/134699306-99798bba-367b-46f4-a70d-f98f12bc06d0.png)

Hey @kylewilliams321 I sent you an invite to my repository.  I only modified the sensor.py but I added heart rate zones and fixed the Current stats.  I can better help you with that file.  Just open an issue there and we can figure it out for you.

**Comment by Finagain** [comment]
> Please, pretty please fix!

I sent you an invite to my fork of this project with updates to the API

**Comment by kylewilliams321** [comment]
I ended up just commenting out the heartbeat specific lines in the Python
script awhile back and it ended up working just fine for me. I don’t think
I ever gave you that update though.

I’m now trying to work in automations that update an LED light strip based
on power w. It’s still a work in progress but the delay is a little tough
to work with.

Does anyone have any automations that they like/suggest?

**Comment by edwork** [comment]
New Release Published - Version 0.6.0!  

https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.6.0

Everything seems to be working now.

**Comment by dgoldy56** [comment]
Thankyou will try, very much appreciate your efforts, nice work
