### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by thomasgregg** [edwork/homeassistant-peloton-sensor#18]
Great work, but would be great to get HACS support.

**Comment by edwork** [comment]
Hello,  

Thanks for filing this Feature Request. This is in the works, just need to file a few changes to the main HACS repository.  

In the meantime the Github HTTP URL can be added as a third party HACS URL and the integration will show up in HACS.  

Thanks!  
Ed

**Comment by thomasgregg** [comment]
Works great. Thanks a lot.

**Comment by edwork** [comment]
Made the appropriate changes and modifications to this repo, awaiting the following PR to the main HACS repo: https://github.com/hacs/default/pull/1153

**Comment by edwork** [comment]
This project has been successfully added as an integration to HACS' default repository, users can simply search for Peloton in HACS to install without having to copy the files into their config folder!
