### ISSUE TITLE
Attribute names

### ISSUE THREAD

**Issue by Cassock** [edwork/homeassistant-peloton-sensor#3]
Good morning and fantastic work on this. I am using this sensor with custom:entity-attributes-card to show some stats from my most recent ride, but it's not clear to me how the attributes are actually named. I've been able to guess at many of them (the single word attributes are obvious) or get close enough with wildcards - for example, sensor.peloton_user.duration* - but some of them I simply can't figure out. Is it possible to list them all here?
![image](https://user-images.githubusercontent.com/15901832/97709162-46c72080-1a90-11eb-9b10-f5e0d0dfd0ea.png)
Thanks!

**Comment by Cassock** [comment]
Ignore. I incorrectly assumed that spaces would be a problem. Formatting multi-word attributes is as easy as `sensor.peloton_user.Speed Max Mph`. Note that the attributes are case sensitive.

**Comment by edwork** [comment]
Hello,

Happy to hear you got it working. This would be a great addition to the documentation. I'll note this down as an action item, as I imagine many users will want to use or display state attributes. 

Cheers!
