### ISSUE TITLE
Bike, Tread and Guide differences

### ISSUE THREAD

**Issue by neildsb** [edwork/homeassistant-peloton-sensor#30]
Thanks Ed love your work and effort, hoping the following observation help? 

The State attributes are quite different, eg there are no ‘Heat Rate’ values on the tread (would love to trigger a fan on the tread) also labeled ‘Prism’, the ‘output Kj’ did not update every 30 secs or so, only on completion and no Calories?

![image](https://user-images.githubusercontent.com/91122872/148255257-f773d3d1-9a02-4a8d-b711-047ee57e5981.png)

**Comment by edwork** [comment]
Hello,  

I have a fix for this landing shortly. Bike, Tread, TV, App workouts all have different attributes and the sensor stops looking for attributes when it fails parsing something. This was unintentional and soon it will lookup all data regardless. 

Thanks for reporting this, I'll update this issue when the fix has been rolled out!

**Comment by edwork** [comment]
Version 0.7.1 has been released which fixes the mismatching number of attributes that are reported during these workouts. Now regardless of the type of workout you are involved in the attributes will populate and where necessary report Unavailable if the values don't exist - for example cadence during a cool down workout on your Apple TV. These types of workouts would previously halt the rest of the attributes values causing the effect in your screenshots. 

As for the values I still need to look into this by seeing what's reported by the API during vs after a ride and how to represent either value. At a glance some of these values are instantaneous and others some type of summary. Should be easy to sort out.

I'd like to gather more data on the tread (and buy one eventually), we can work on making this integration relevant to all types of workouts. 

Thanks for the feedback!

**Comment by neildsb** [comment]
thanks Ed, highly recommend the tread :-), I have some screenshots, hope this helps?

![image](https://user-images.githubusercontent.com/91122872/148516971-79c008f8-cb73-4fe1-8539-afc80a492078.png)

**Comment by neildsb** [comment]
thanks Ed, highly recommend the tread :-), i have some screenshots, hope this helps?

![image](https://user-images.githubusercontent.com/91122872/148516971-79c008f8-cb73-4fe1-8539-afc80a492078.png)

**Comment by neildsb** [comment]
the 'Peloton Guide' arrive today and taking a strength class the fan automation trigger started up no problems, that's good :-) Hope this helps?

![image](https://user-images.githubusercontent.com/91122872/162205733-4ad383df-9248-4d96-9f8a-cb6509ff85b4.png)
