### ISSUE TITLE
no longer working

### ISSUE THREAD

**Issue by dgoldy56** [edwork/homeassistant-peloton-sensor#37]
stopped working after new release upgrade 2022.6

**Comment by edwork** [comment]
Hello,

Thanks for reporting this. I'm currently personally running 2022.6.3 and still pulling in sensor data on version 0.71 (latest). Can you please tell me:
- What version you are running
- How you installed the sensor (HACS, manual download)
- Any logs with tracebacks from the integration.

Thanks! In the meantime I'll do some poking around. 
-Ed

**Comment by neildsb** [comment]
if it helps? it's all still working on my setup in the UK -

Home Assistant Core 2022.6.3
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

**Comment by dgoldy56** [comment]
I will try when home later and see but Sunday in US nothing was there.  Running 0.7.1 with latest  HA (2022.6.3 - last night .2 prior)

**Comment by edwork** [comment]
Hello,

Please try again with the most recent release, this release includes a setup configuration flow from the HomeAssistant UI. See the readme page for details. 

Thanks!

**Comment by dgoldy56** [comment]
Sorry was overwhelmed with work looks like it’s ok data is being pulled in. I had card like yours and did not populate that was error

**Comment by edwork** [comment]
Happy things are working again. Feel free to open another issue if you experience anymore problems.

**Comment by dgoldy56** [comment]
Sorry never got back to you everything working very nicely – thanks again for the addin
