### ISSUE TITLE
Not available in config flow

### ISSUE THREAD

**Issue by holman** [edwork/homeassistant-peloton-sensor#40]
Hi! Just tried installing via HACS and I couldn't find it in the "Add integration" UI to actually install and configure it.

Then I stumbled on #38 and saw that the 0.8 release hadn't been cut yet, so I tracked the master branch in HACS, restarted, confirmed it had the newest version on-disk, and... still can't find it in the UI to actually add it to my HA instance.

Not entirely sure what might be the issue here- I can see in the logs that HA notices there's a Peloton integration, but besides the initial `We found a custom integration peloton` message, it doesn't output anything else.

Happy to dig into things further!

**Comment by edwork** [comment]
Hello, I am in the middle of a few things and will upload the release tonight. Part of my hesitation is just around the wording the PR portion of things - as when 0.8 is released everyone's integration will break and need re-setup. 

Expect an update soon

**Comment by holman** [comment]
Will give it a look when it's officially released! (Though I would have expected what's on the `master` branch as 0.8 would go through the config flow already, but maybe that's not the case.)

**Comment by edwork** [comment]
Done - released [here](https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.8)!

Thanks for reporting this issue, helps remind me of the growing interest in the integration. For HACS, it takes a look at releases posted with a .zip file which defines the HACS release. 

Cheers!

**Comment by holman** [comment]
Can confirm it works with the new release- thanks so much!

**Comment by edwork** [comment]
Excellent! Enjoy, and please feel free to report any other findings.
