### ISSUE TITLE
became unavailable

### ISSUE THREAD

**Issue by neildsb** [edwork/homeassistant-peloton-sensor#41]
Just tried the latest version on the bike and tread, the UI integrations works, but when I start a class, it does not work :-(

Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1

![image](https://user-images.githubusercontent.com/91122872/173528065-2aab805b-587e-4767-8613-8797132a8ec2.png)

This error originated from a custom integration.

Logger: custom_components.peloton
Source: custom_components/peloton/__init__.py:249
Integration: Peloton (documentation, issues)
First occurred: 9:09:52 am (3 occurrences)
Last logged: 9:10:16 am

Unexpected error fetching peloton data: an integer is required (got type NoneType)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 191, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 150, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/peloton/__init__.py", line 75, in async_update_data
    "quant_data": compile_quant_data(
  File "/config/custom_components/peloton/__init__.py", line 249, in compile_quant_data
    datetime.fromtimestamp(workout_stats_summary["end_time"], user_timezone)
TypeError: an integer is required (got type NoneType)

**Comment by curt7000** [comment]
Same here, running HA Core 2022.06.5.  When I start a workout, all entities go to 'Unavailable', when workout stops, all entities return.

**Comment by gregorymartin** [comment]
I am experiencing the same issue as well.

**Comment by neildsb** [comment]
8.1 is working, thanks, also upgrade HA

Home Assistant Core 2022.6.6
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2
