### ISSUE TITLE
Heartrate

### ISSUE THREAD

**Issue by Bubbalax** [edwork/homeassistant-peloton-sensor#44]
I created automations based on current heartrate with the old integration. This does not seem possible with the current integration. I only see Avg HR and Max HR. Am I missing something? 

BTW - Great work on this integration. Thank you!

**Comment by edwork** [comment]
Hello!

I haven't lost track of this, at a quick glance I think I see the current heart rate is still populated in my latest workout overview. I'll try and add it back shortly.

Thank you for the feedback and for enjoying the integration!
-Ed

**Comment by tamu20** [comment]
+1 on this request.  Most of my automations are based on the previous 'current heartrate' sensor.

Thanks again for your time on this integration.

**Comment by Bubbalax** [comment]
Hi Ed.
I am circling back on this one. I am not trying to push but curious if still plan on addressing this. Thank for you the latest release!

**Comment by Miablo** [comment]
@Bubbalax @tamu20 i just got some code merged into master that should bring back this functionality 🤞

**Comment by Bubbalax** [comment]
@Miablo - Any way I can manually update the change? Its Winter and I would like to play with it! :) Thank you!

**Comment by edwork** [comment]
[Version 0.9.0 has been released](https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.9.0) and now fully supports theses values. Feel free to open this issue back up if you run into anything unexpected. 

Thanks!
