### ISSUE TITLE
Primary State

### ISSUE THREAD

**Issue by tamu20** [edwork/homeassistant-peloton-sensor#47]
Is it possible to add the primary state back to the new code?  It was easy to track if a workout was happening by just triggering off the 'Active' status vs Complete.

`        # Update Primary State
        if (workout_latest["status"]== 'COMPLETE'):
            self._state = 'Complete'
        elif (workout_latest["status"]== 'IN_PROGRESS'):
            self._state = 'Active'
        else:
            self._state = 'Unavailable'
`

Thank you for a great plugin.

**Comment by tamu20** [comment]
Nevermind - I see it in the binary sensor area.

**Comment by edwork** [comment]
If it helps I can create a template sensor that acts like the old sensor. 

New sensor types were created to align better with what HomeAssistant wishes sensors look like but I understand that it breaks a lot of automations (including my own) without refactoring them. 

I'll make something and throw it in the readme.

**Comment by tamu20** [comment]
The way you have it works, I just did not see it initially.  I don't mind editing my automations to reference the new sensors.
