### ISSUE TITLE
Values do not reflect actuals

### ISSUE THREAD

**Issue by Some1Elsewhere** [edwork/homeassistant-peloton-sensor#51]
I really love, that you made the effort of trying to get the Peloton readouts integrate with Home Assistant.
In my Setup however, the values are not updated properly, workouts are not recognized or updated. E.g I did two rides yesterday, today it only shows only one rides values. Also, do I need to reset the values to 0 each day with an automation (calories, distance etc.)?

**Comment by edwork** [comment]
Hello,

Thanks for using the integration. The intended use of the integration is to give the user real-time statistics of the most recent ride indexed in their peloton account. Both a ride in-progress or a ride you've just completed is intended to populate the statistics of the sensors.  

The reasoning for this is to give HomeAssistant the ability to switch lights and fans on or off, or say turn a light strip red when the user's heart rate reaches a high zone for example. Viewing statistics historically could be done by HomeAssistant's frontend features but it isn't really in scope or in line with HomeAssistant to add previous ride sensors, etc. Additionally sensors aren't intended to reset, but the main `binary_sensor.person_on_peloton` will flip back to off when the ride is complete. 

I'll consider this for future features or future frontend template ideas, hope this helps clarify.

**Comment by Some1Elsewhere** [comment]
Hi Ed, 

thanks for clarifying this. Now it all makes sense. For me as an avid rider athlete, I use Home Assistant also as a personal health Dashboard. Therefore I can see at a glance my personal performance improvements over time, collecting from all the different sources, garmin/ withings/ etc. peloton was the one missing since there is no strava integration. I think for sport enthusiasts this would really help in monitoring training progress. I hope some day you find the time to integrate this. thanks again.

**Comment by edwork** [comment]
Marking fixed for now as the scope of the sensor is to report current/most recent ride data. For historical data it's recommended to use the recorder to display various datapoints or pump the data into Influx for long term analysis. Otherwise we would have to return too many sensors for X rides back.
