### ISSUE TITLE
fail in version 2023.3

### ISSUE THREAD

**Issue by neildsb** [edwork/homeassistant-peloton-sensor#71]
Hi Ed, FYI

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for peloton using this method at custom_components/peloton/__init__.py, line 98: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Comment by edwork** [comment]
Good news - this was fixed in #63 thanks to @RobertD502. I'm aiming to have the next release out this week, but have been hung up on a few other bugs I was hoping to have resolved all together.
