### ISSUE TITLE
Can't change password

### ISSUE THREAD

**Issue by daveismith** [edwork/homeassistant-peloton-sensor#84]
I recently changed my peloton password and the integration in home assistant now fails. It says "Failed to set up: Login Failed". There's no menu option to re-configure my credentials.

**Comment by edwork** [comment]
Hello,

In the meantime as long as you didn't change your entity names manually, removing the integration and re-adding the integration shouldn't break anything. I'll look into adding some logic to allow users to log back in.

Thanks,  
Ed
