### ISSUE TITLE
Updating to 10.0: Index out of Range

### ISSUE THREAD

**Issue by CaptainFun85** [edwork/homeassistant-peloton-sensor#85]
after updating to 10.0, I am receiving the following error:

Retrying setup: list index out of range

any tips to get back online? Thanks.

**Comment by CaptainFun85** [comment]
This may have been the fix.
I hadnt taken a peloton workout in 4 days. I just took an app workout this afternoon, and shortly after i noticed the integration is working.

**Comment by edwork** [comment]
I'll keep an eye out for this issue, thanks for the report. Let's leave this issue open for a bit and see if anyone else reports the same. 

Thanks!

**Comment by edwork** [comment]
Closing this specific instance of the error, but in issue #89 I'm working to add additional error handling logic that should catch some of these errors if they pop up in the future.
