### ISSUE TITLE
End Time always = Start Time during workout

### ISSUE THREAD

**Issue by JonSilver** [edwork/homeassistant-peloton-sensor#86]
The end time is always the start time during a workout. Therefore there's no way of displaying the actual estimated end time allowing for any pauses.

If there's no pause (almost always the case), then start time plus duration works nicely - and that's what I'm using at the moment.

Why this is important: my wife likes to know when I'll be done without coming in and disturbing my mojo. 😁

**Comment by Flintr** [comment]
+1 from me as well. Currently using a template to calculate expected end time as start time + duration, but the native end time entity should do that on its own.

**Comment by edwork** [comment]
On my radar - I'll work on adding this as a first party sensor.
