### ISSUE TITLE
Add a version into manifest

### ISSUE THREAD

**Issue by superm1** [edwork/homeassistant-peloton-sensor#9]
Including this custom component in, I notice that HA marks it as it won't be supported in upcoming release without adding an extra key to the manifest.

>No 'version' key in the manifest file for custom integration 'peloton'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'peloton'

Can you add this in the future?

**Comment by edwork** [comment]
Hello!

Thanks for reporting this issue. The version tag was added via Pull #6. Maybe you're running a version <0.5? If so check out https://github.com/edwork/homeassistant-peloton-sensor/releases/tag/0.5

Hope this helps, let me know if it doesn't.

Thanks,  
Ed

**Comment by superm1** [comment]
Yup, I think that was it, thanks!

FYI for you, I notice it's still not working - but it looks like it's a problem with your dependency, you might want to keep an eye here: https://github.com/justmedude/pylotoncycle/pull/10.  Probably need to bump your dep after that's sorted.
