### ISSUE TITLE
Current values/sensors don't drop to zero when not in use

### ISSUE THREAD

**Issue by benjec83** [edwork/homeassistant-peloton-sensor#90]
I don't know if this is a problem on my end, or just how the sensors work, but sensors like current cadence/resistance/heart rate/speed don't zero out when a workout isn't in progress/running. What ever the final value was of the workout, is the persistent value until you workout again.

**Comment by edwork** [comment]
Hello,  

This is a symptom of what the API returns when a workout is not in progress. I'll re-evaluate what should be returned for each sensor while a ride is not in progress as I agree - stuck values don't exactly make sense while not in use. The impact could be automations that rely on heart rate might be stuck forever in a 'high' state.

Thanks for the feedback!
